### ISSUE TITLE
String concatenation not working

### ISSUE THREAD

**Issue by karakanb** [NikolaLohinski/gonja#12]
Hey, thanks a lot for the work, this helps a lot. I intend to use this with [Bruin](https://github.com/bruin-data/bruin) instead of the old fork, and ran into a behavior that doesn't seem to be working with concatenation:

`{{ "asd" + "xyz" }}`
- gonja output: `0`
- jinja2 output: `asdxyz`

```
{%- set a = "asd" -%}
{{ a + "xyz" }}
```
- gonja output: `0`
- jinja2 output: `asdxyz`

any ideas on how to circumvent / fix the issue?

**Comment by karakanb** [comment]
It took me 12mins to create a fix for this from scratch without ever seeing this project at all, such an intutive codebase, not sure if it was you or the original fork but thanks!

**Comment by NikolaLohinski** [comment]
Thanks for reporting the issue ! It's definitely a bug we want fixed.

Regarding: 
> It took me 12mins to create a fix for this from scratch without ever seeing this project at all, such an intutive codebase, not sure if it was you or the original fork but thanks!

It's both the original project that was well implemented feature-wise, and a lot of refactoring when I took over to make it robust, more unit-testable, and organized in a better way.

**Comment by NikolaLohinski** [comment]
@karakanb , this has been released in `v2.1.4`, enjoy :)
