### ISSUE TITLE
missing variables are logged but no error returned

### ISSUE THREAD

**Issue by karakanb** [NikolaLohinski/gonja#14]
take a look at the following reproduction:

```go
package main

import (
	"fmt"
	"os"

	"github.com/nikolalohinski/gonja/v2"
)

func main() {
	template, err := gonja.FromString("{% for day_n in days %}{{ day_n }}{% endfor %}")
	if err != nil {
		panic(err)
	}

	err = template.Execute(os.Stdout, nil)
	if err != nil {
		panic(err)
	}

	fmt.Println("error is nil")
}
```

This code outputs the following:
```
ERRO[0000] Value.Iterate() not available for type: invalid 
error is nil
```

This means that I am unable to handle the error in the application when this happens when the variable is missing. This is a common enough usecase, therefore I was expecting to get an error but instead it seems to be logging the error.

## Expected Behavior
I'd expect the `template.Execute` call to return an error with the details of the issue, and nothing to be logged by the library.

**Comment by NikolaLohinski** [comment]
Hi @karakanb,

That's expected behavior, and you should get the same behavior with regular Python Jinja.

If you wish the engine to fail on a missing variable, you need to set the `Config` field `StrictUndefined` to `true`.

Hope it helps, and if not, let me know.

Cheers 🤘🏻
