### ISSUE TITLE
Template render result is incompatible with Jinja2

### ISSUE THREAD

**Issue by iredmail** [NikolaLohinski/gonja#18]
https://github.com/NikolaLohinski/gonja/blob/master/tests/integration/config_test.go#L136

gonja requires additional whitespace control `{%-` to generate same result of Jinja2:
```
// gonja
{%- set block_example = "test" %}

// Jinja2
{% set block_example = "test" %}
```

Python3 + Jinja2:
```
from jinja2 import Environment, PackageLoader, select_autoescape
env = Environment(trim_blocks=True)

tmpl = """{% if one %}
    - 1
{% endif %}
{% if two %}
    - 2
{% endif %}
{% if three %}
    - 3
{% endif %}
"""

template = env.from_string(tmpl)
print(template.render(one=True, two=True, three=True))
```

Output:
```
    - 1
    - 2
    - 3

```

Sample gonja code:
```
package main

import (
	"os"

	"github.com/nikolalohinski/gonja/v2"
	"github.com/nikolalohinski/gonja/v2/exec"
)

var tmpl = `{% if one %}
    - 1
{% endif %}
{% if two %}
    - 2
{% endif %}
{% if three %}
    - 3
{% endif %}
`

func main() {
	c := gonja.NewConfig()
	c.TrimBlocks = true
	gonja.DefaultConfig = c

	t, _ := gonja.FromString(tmpl)
	data := exec.NewContext(map[string]interface{}{
		"one":   true,
		"two":   true,
		"three": true,
	})

	_ = t.Execute(os.Stdout, data)
}
```

Output:
```
    - 1

    - 2

    - 3

```

**Comment by NikolaLohinski** [comment]
Hi @iredmail and thanks for reporting.

It should be fixed with https://github.com/NikolaLohinski/gonja/commit/e6a8c100d0d4247f6911644e3dfcee0e0b84b2cd and is released in https://github.com/NikolaLohinski/gonja/tree/v2.2.2.

Let me know if it works for you and if not feel free to reopen the issue.

Cheers

**Comment by iredmail** [comment]
It works. Thank you very much. :)

**Comment by iredmail** [comment]
By the way, i suppose the variable name `lineReturnWithOnlyWitheSpace` should be `lineReturnWithOnlyWhiteSpace` (Withe -> White)?
https://github.com/NikolaLohinski/gonja/commit/e6a8c100d0d4247f6911644e3dfcee0e0b84b2cd#diff-e7aabff4498aa61c581fe6fd5c90c50da24b02b88f32d75238a5dc37edaaa794R16

**Comment by NikolaLohinski** [comment]
Ah good catch, thanks ! Fixed ✅
