### ISSUE TITLE
How can I use config to change the variable start and end string

### ISSUE THREAD

**Issue by sunshine69** [NikolaLohinski/gonja#21]
Not so clear, I have not read the source code but from doco and vscode completeion there seems none.

Basically in the below, I can customise the config, but how I set it in the template ?

If it is impossible then the config should be marked as private.

I also tried v1.5.3 while I can produce compile code but when run it does not take effect. 

```
// v2 code
func main() {
	cfg := config.Config{
		VariableStartString: "{$",
		VariableEndString:   "$}",
	}

	tpl, err := gonja.FromString("Hello, {{ name }}!")
	if err != nil {
		panic(err)
	}
	data := exec.NewContext(map[string]interface{}{"name": "World"})

	output, err := tpl.ExecuteToString(data)
	if err != nil {
		panic(err)
	}
	fmt.Println(output)
}
```

v1 code below but it does not work

```
func main() {
	cfg := config.Config{
		Debug:               true,		
		VariableStartString: "{$",
		VariableEndString:   "$}",
	}

	env := gonja.NewEnvironment(&cfg, gonja.DefaultLoader)

	tpl, err := env.FromString("Hello, {$ name $}!")
	if err != nil {
		panic(err)
	}
	context := map[string]interface{}{"name": "World"}
	output, err := tpl.Execute(context)
	if err != nil {
		panic(err)
	}
	fmt.Println(output)
}
```

pls help.

cheers

**Comment by sunshine69** [comment]
Also it would be good to give examples of how to create custom filter for example.

**Comment by sunshine69** [comment]
Further reading I tried code like this but then the lexer does nto like it

```
package main

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"os"

	"github.com/nikolalohinski/gonja/v2"
	"github.com/nikolalohinski/gonja/v2/config"
	"github.com/nikolalohinski/gonja/v2/exec"
	"github.com/nikolalohinski/gonja/v2/loaders"
)

func FromBytesWithConfig(source []byte, config *config.Config) (*exec.Template, error) {
	rootID := fmt.Sprintf("root-%s", string(sha256.New().Sum(source)))

	loader, err := loaders.NewFileSystemLoader("")
	if err != nil {
		return nil, err
	}
	shiftedLoader, err := loaders.NewShiftedLoader(rootID, bytes.NewReader(source), loader)
	if err != nil {
		return nil, err
	}
	return exec.NewTemplate(rootID, config, shiftedLoader, gonja.DefaultEnvironment)
}

func FromStringWithConfig(source string, config *config.Config) (*exec.Template, error) {
	return FromBytesWithConfig([]byte(source), config)
}

func main() {
	cfg := config.Config{
		VariableStartString: "{$",
		VariableEndString:   "$}",
	}

	tpl, err := FromStringWithConfig("Hello, {$ name $}!", &cfg)
	if err != nil {
		panic(err)
	}
	context := exec.NewContext(map[string]interface{}{"name": "World"})
	err = tpl.Execute(os.Stdout, context)
	if err != nil {
		panic(err)
	}
}

```

panic: runtime error: index out of range [-1]

goroutine 18 [running]:
github.com/nikolalohinski/gonja/v2/tokens.(*Lexer).lexComment(0xc000104e70)
        /home/stevek/go/pkg/mod/github.com/nikolalohinski/gonja/v2@v2.2.3/tokens/lexer.go:275 +0x1e5
github.com/nikolalohinski/gonja/v2/tokens.(*Lexer).Run(...)
        /home/stevek/go/pkg/mod/github.com/nikolalohinski/gonja/v2@v2.2.3/tokens/lexer.go:104
created by github.com/nikolalohinski/gonja/v2/tokens.Lex in goroutine 1
        /home/stevek/go/pkg/mod/github.com/nikolalohinski/gonja/v2@v2.2.3/tokens/lexer.go:71 +0x59
exit status 2

**Comment by sunshine69** [comment]
Yeah just realize that I have to fill all of the Config and it works fine

I am thiking a better way to use it for end user ...

**Comment by NikolaLohinski** [comment]
Hi @sunshine69 and than you for opening the issue.

First of all, as decribed in the general README (see [this](https://github.com/NikolaLohinski/gonja?tab=readme-ov-file#migrating-from-v1-to-v2)), I am not supporting the v1 of the library ; please use the migration notes if you need to switch frm v1 to v2.

Now , regarding your issues : I 100% agree with you that the docs could be made a bit clearer. Feel free to submit a PR to fix things and I'd be happy to review/merge it.

The TL;DR is that you can either:
- rely on the defaults (obviously not what you want :wink: )
- override the global config variable
- redefine everything yourself

Here's an example of full config redefining https://github.com/NikolaLohinski/terraform-provider-jinja/blob/main/lib/render.go#L137

As of this writing, there's no helper function such as `FromString` or `FromFile` that allows using a custom configuration, but if you feel like there's a need for it, I'd be super happy to take a PR for it. Something like `FromFileWithConfig` as you suggested in your example would work perfectly.

Hope it helps and LMK if not,

Cheers

**Comment by sunshine69** [comment]
I implement something currently on my local lib, will try to find a proper place to put it. I also add regex_search (well it standard jinja2 so not sure if u are interested) - regex_replace and to_yaml, to_json filters.

If these filter are of valuable pls let me know I will create a PR. But I need to look more into how to add these unit tests required by you, currently it is just implementation.

Ta

**Comment by NikolaLohinski** [comment]
Hi @sunshine69 

Regarding custom filter, I would like to stick with regular filters available in native Python jinja.

The goal of this library is to provide a 1 to 1 mapping between go and Python for Jinja templates and adding extra logic in the filters would break that purpose.

If you need additional filters, you can easily import all of the custom filters and functions from the the terraform-provider-jinja/lib. There's quite a few including those you mentioned. 

Hope it helps,

Cheers
