### ISSUE TITLE
Unable to parse controlStructure "for": expected either a number, string, keyword or identifier. (Line: 3 Col: 28, near "*")

### ISSUE THREAD

**Issue by zhangguanzhang** [NikolaLohinski/gonja#24]
```
package main

import (
	"os"

	"github.com/nikolalohinski/gonja/v2"
	"github.com/nikolalohinski/gonja/v2/exec"
)

func main() {
	template, err := gonja.FromString(`
{% for v in "a=b,c=d".split(",") %}
      {{ "%s: '%s'"|format(*(v.split("="))) }}
{% endfor %}
`)
	if err != nil {
		panic(err)
	}

	data := exec.NewContext(map[string]interface{}{
		"name": "bob",
	})
	
	if err = template.Execute(os.Stdout, data); err != nil { // Prints: Hello Bob!
		panic(err)
	}
}
```

works fine on ansible template:
```
  tasks:
  - name: test
    template: src=test.tpl.j2 dest=/tmp/test
```
`templates/test.tpl.j2`:
```
{% for v in "a=b,c=d".split(",") %}
      {{ "%s: '%s'"|format(*(v.split("="))) }}
{% endfor %}
```

result is:
```
$ cat /tmp/test
      a: 'b'
      c: 'd'

```

**Comment by NikolaLohinski** [comment]
Hey @zhangguanzhang , and thanks for the bug report

Indeed, the dereferencing using `*`  (which in this case unpacks the array returned by the split function as arguments of the format filter) is not something that is supported in `gonja`.

Long term, that is something that seems worth implementing to me, but requires some work to create a new node type in the parser and a new handler in the renderer. Nothing horribly complicate, but just some work, so let's keep the issue open for that.

Short term, might I suggest using a more "jinja native" approach to achieve the same result ? :point_down: 
```
{% for v in "a=b,c=d".split(",") %}
      {%- set keyValue = v.split("=") %}
      {{ "%s: '%s'" | format(keyValue[0], keyValue[1]) }}
{% endfor %}
```

Cheers

**Comment by zhangguanzhang** [comment]
> Hey @zhangguanzhang , and thanks for the bug report
> 
> Indeed, the dereferencing using `*` (which in this case unpacks the array returned by the split function as arguments of the format filter) is not something that is supported in `gonja`.
> 
> Long term, that is something that seems worth implementing to me, but requires some work to create a new node type in the parser and a new handler in the renderer. Nothing horribly complicate, but just some work, so let's keep the issue open for that.
> 
> Short term, might I suggest using a more "jinja native" approach to achieve the same result ? 👇
> 
> ```
> {% for v in "a=b,c=d".split(",") %}
>       {%- set keyValue = v.split("=") %}
>       {{ "%s: '%s'" | format(keyValue[0], keyValue[1]) }}
> {% endfor %}
> ```
> 
> Cheers

Thank you very much. The code you suggested works exactly as I expected. I was just being too stupid to figure it out.🎉🎉🎉
