### ISSUE TITLE
Bug: String comparison not behaving the same way as Jinja

### ISSUE THREAD

**Issue by karakanb** [NikolaLohinski/gonja#30]
Here's a simple example with Python Jinja:

```python
from jinja2 import Template
print(Template('"a" < "b": {{ "a" < "b" }}').render())
```
You can run this with the following command if you have `uv` installed:
```bash
uv run --no-project --with "jinja2" --script reproduction.py
```

The output is this:
```
"a" < "b": True
```

However, when I do the same with Gonja on v2.3.3, the output I get is this:
```golang
package main

import (
	"fmt"
	"github.com/nikolalohinski/gonja/v2"
)

func main() {
	tpl, err := gonja.FromString(`"a" < "b": {{ "a" < "b" }}`)
	if err != nil {
		panic(err)
	}

	res, err := tpl.ExecuteToString(nil)
	if err != nil {
		panic(err)
	}
	fmt.Println(res)
}
```
```
"a" < "b": False
```

Either I am doing something wrong, or there's an incompatibility with jinja with regards to this.

**Comment by NikolaLohinski** [comment]
Hey @karakanb and thanks for the report.

Indeed the behavior in Python when comparing strings with those operators is to do lexicographic comparison.

This should be fairly simple to fix, by doing the proper comparing.

If you feel like doing the PR, I'll be happy to merge it 

Cheers
