### ISSUE TITLE
New line inside double bracket generate err.

### ISSUE THREAD

**Issue by mquinteiro** [NikolaLohinski/gonja#6]
When I try to use a template saved from a component that breaks lines automatically  some times it's break the inter {{ }} with a \n inside, that makes the the system to fail.
Example:
```

package main

import (
	"fmt"

	"github.com/nikolalohinski/gonja"
)

func main() {
	template_string := ` {{\n data.name}} `
	tpl, err := gonja.FromString(template_string)
	if err != nil {
		fmt.Println(err)
		return
	}
	ctx := gonja.Context{
		"data": map[string]string{
			"name": "Nikola",
		},
	}
	out, err := tpl.ExecuteBytes(ctx)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(out))

}

```

It fails with err: '}}' expected here (Line: 1 Col: 7, near "data")
Have sense to remove all the \n inside {{ }} or can it have side effects?

Is it safe to change the method 
```
func (s *Stream) nonIgnored() *Token {
	var tok *Token
	for tok = s.it.Next(); tok.Type == Whitespace; tok = s.it.Next() {
	}
	return tok
}
```

To something like ` tok.Type == Whitespace || tok.Type == Newline `

**Comment by mquinteiro** [comment]
My fault, it was not a \n is was a literal \n, that is \\n what makes me wrong. 
The package works as I expected.

**Comment by NikolaLohinski** [comment]
Hi @mquinteiro and thank you for your question.

In my opinion, I think it's best to stay close to what python jinja does. Trying a similar as to what you suggested example on https://j2live.ttl255.com/ tells me it should error out the same way multiline template blocks are invalid.

Regarding your question:
> Have sense to remove all the \n inside {{ }} or can it have side effects?

I am not sure what could happen. The parser is not designed to handle multiline blocks, so anything could happen.
