### ISSUE TITLE
% if string not in string %: If-condition is malformed

### ISSUE THREAD

**Issue by VladimirBlinov** [NikolaLohinski/gonja#7]
Panic "Unable to parse statement "if": If-condition is malformed." with template

{% if contact.1 != '' and 'test' not in contact.1|lower %}
Hello, {{contact.1|lower|capitalize}}!
{% else %}
Hello!
{% endif %}

{% if contact.1 != '' and 'test' not in contact.1|lower %} - error
{% if contact.1 != '' and 'test' in contact.1|lower %} - not error. But when 'test' is not in real contact.1, "true" path is executed. Not "else" path.

**Comment by NikolaLohinski** [comment]
Hi @VladimirBlinov for pointing it out. It is fixed in [`v1.5.1`](https://github.com/NikolaLohinski/gonja/tree/v1.5.1). Let me know if you have other issues and feel free to close this one

cheers

**Comment by VladimirBlinov** [comment]
fixed in 1.5.1
