### ISSUE TITLE
substring using brackets not supported e.g. {{ "substring"[:2] }}

### ISSUE THREAD

**Issue by Zatte** [NikolaLohinski/gonja#9]
Hi, 

First, thank you for carrying the troch and maintaining the fork; great work! 

Found this issue. 
```
func TestGonja4SubStringIndex(t *testing.T) {
	t.Parallel()

	template, err := upstream_gonja.FromString(`{{ dynVariable[:2] }}`)
	if err != nil {
		t.Fatalf("failed to parse template: %v", err)
	}

	res, err := template.Execute(map[string]interface{}{
		"dynVariable": "foo bar",
	})
	if err != nil {
		t.Fatalf("failed to parse template: %v", err)
	}

	if strings.Trim(res, " ") != "fo" {
		t.Fatalf("expected 'foo', got: %s", res)
	}
}
```
=> 
`failed to parse template: Invalid expression (Line: 2 Col: 18, near ":")`

Haven't found the specification saying that this should be supported though it seems to be by most implementations. Would be swell if it got supported but understand time is limited :)

**Comment by NikolaLohinski** [comment]
Hey @Zatte thzt shoudn't be too hard to add. I am currently focusing on fixing bugs and moving to the terraform plug-in framework. But after that I can take a peek and get it done.

Otherwise feel free to make a PR, and I ´ll help you get it working and merged

Cheers

**Comment by NikolaLohinski** [comment]
Hi @Zatte 

I've just pushed `v2.0.0` which has the feature you requested.

This is major one, so the upgrade might not be trivial, but I've put [these small steps](https://github.com/NikolaLohinski/gonja?tab=readme-ov-file#migrating-from-v1-to-v2) together to help you out.

Let me know if you run into any issues

Cheers

**Comment by Zatte** [comment]
Great job; will have a look at it soon, the changes seems well documented and sane so shouldn't be to difficult to migrate. 

Once again many thanks for maintaining this fork!
